### ISSUE TITLE
V0.2.0 (Make this in Julia)

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLangSlack/StackOverflowBot#4]
Make this in Julia.

**Comment by asinghvi17** [comment]
`from stackapi import StackAPI`

Is there an equivalent package in Julia?  Otherwise, we'll have to make one.  Shouldn't be too hard, though/

**Comment by logankilpatrick** [comment]
I don’t think that that package is really helping with much. We could probably make do without it.

Best, 
Logan Kilpatrick

**Comment by logankilpatrick** [comment]
Done!
